-- Palabre — production Sénégal : quiz « Testez-vous »
-- Généré par gen_sql.py depuis les fichiers de recherche sourcés.
-- Chaque ligne porte sa source. Aucune donnée fictive.
-- À exécuter avec : supabase db query --linked -f <ce fichier>

begin;


insert into public.quiz (id, country_code, titre, version, publie) values
  (1, 'SN', 'Testez-vous · Sénégal 2026', 1, false);

insert into public.statement (id, quiz_id, ordre, texte, theme) values
  (1, 1, 1, 'Le mandat présidentiel doit être limité à deux mandats, sans possibilité de révision de cette règle.', 'institutions'),
  (2, 1, 2, 'Le poste de Premier ministre doit être maintenu dans la Constitution.', 'institutions'),
  (3, 1, 3, 'Les députés doivent publier chaque mois leur présence en séance et en commission.', 'institutions'),
  (4, 1, 4, 'Le parquet doit être indépendant du ministre de la Justice.', 'justice'),
  (5, 1, 5, 'Les décisions de justice doivent être publiées en ligne, accessibles à tous.', 'justice'),
  (6, 1, 6, 'L''État doit renégocier les contrats pétroliers et gaziers signés avant 2024.', 'economie'),
  (7, 1, 7, 'Le prix du carburant à la pompe doit être plafonné par l''État, même si cela coûte au budget.', 'economie'),
  (8, 1, 8, 'Le Sénégal doit sortir du franc CFA pour une monnaie nationale ou régionale nouvelle.', 'economie'),
  (9, 1, 9, 'Les entreprises publiques déficitaires doivent être ouvertes au capital privé.', 'economie'),
  (10, 1, 10, 'La dette publique doit être réduite en priorité, même au prix d''une baisse des dépenses de l''État.', 'economie'),
  (11, 1, 11, 'Les accords de pêche avec des flottes étrangères doivent être suspendus.', 'agriculture'),
  (12, 1, 12, 'Les subventions agricoles doivent aller en priorité aux exploitations familiales.', 'agriculture'),
  (13, 1, 13, 'Les langues nationales doivent être langues d''enseignement dès le primaire, aux côtés du français.', 'education'),
  (14, 1, 14, 'Les écoles coraniques (daaras) doivent être intégrées au système public et financées par l''État.', 'education'),
  (15, 1, 15, 'L''orientation vers les universités publiques doit être conditionnée à une sélection à l''entrée.', 'education'),
  (16, 1, 16, 'La couverture maladie universelle doit être obligatoire et financée par l''impôt.', 'sante'),
  (17, 1, 17, 'Chaque département doit disposer d''un hôpital de niveau 2 avant 2030.', 'sante'),
  (18, 1, 18, 'Les bourses familiales doivent être étendues à tous les ménages sous le seuil de pauvreté.', 'social'),
  (19, 1, 19, 'Le salaire minimum doit être revalorisé chaque année en fonction de l''inflation.', 'social'),
  (20, 1, 20, 'Les maires doivent être élus au suffrage universel direct.', 'decentralisation'),
  (21, 1, 21, 'Une part fixe du budget de l''État doit être transférée aux collectivités territoriales.', 'decentralisation'),
  (22, 1, 22, 'Les sachets et emballages plastiques à usage unique doivent être interdits et l''interdiction appliquée.', 'environnement'),
  (23, 1, 23, 'Le Sénégal doit exploiter pleinement son pétrole et son gaz avant de réduire les énergies fossiles.', 'environnement'),
  (24, 1, 24, 'La Casamance doit obtenir un statut spécial de décentralisation renforcée.', 'securite'),
  (25, 1, 25, 'Les Sénégalais de l''extérieur doivent pouvoir voter en ligne aux élections nationales.', 'diaspora');

insert into public.party_position (statement_id, org_id, position, source_type, source_url, source_extrait, date_source) values
  (1, 1, 'sans_position', 'aucune', null, null, null),
  (1, 2, 'sans_position', 'aucune', null, null, null),
  (1, 3, 'sans_position', 'aucune', null, null, null),
  (1, 4, 'sans_position', 'aucune', null, null, null),
  (1, 5, 'sans_position', 'aucune', null, null, null),
  (1, 6, 'sans_position', 'aucune', null, null, null),
  (1, 7, 'sans_position', 'aucune', null, null, null),
  (1, 8, 'sans_position', 'aucune', null, null, null),
  (1, 9, 'sans_position', 'aucune', null, null, null),
  (1, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Nous ratifierons le nouveau protocole de la CEDEAO sur la limitation des mandats présidentiels à deux et pèserons de toute notre influence diplomatique afin que cette résolution fasse l’unanimité dans l’espace CEDEAO. […] par la Commission Nationale de Réforme des Institutions (CNRI). Son caractère sacré sera renforcé par des procédures rigides d’amendement précisant les domaines modifiables uniquement par référendum et les parties modifiables par le Parlement à une majorité qualifiée ;', '2024-03-20'),
  (2, 1, 'sans_position', 'aucune', null, null, null),
  (2, 2, 'sans_position', 'aucune', null, null, null),
  (2, 3, 'sans_position', 'aucune', null, null, null),
  (2, 4, 'sans_position', 'aucune', null, null, null),
  (2, 5, 'sans_position', 'aucune', null, null, null),
  (2, 6, 'sans_position', 'aucune', null, null, null),
  (2, 7, 'sans_position', 'aucune', null, null, null),
  (2, 8, 'sans_position', 'aucune', null, null, null),
  (2, 9, 'sans_position', 'aucune', null, null, null),
  (2, 13, 'desaccord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Nous instaurerons le poste de vice-président, élu en tandem avec le Président de la République et supprimerons le poste de premier ministre. Les prérogatives institutionnelles de chacune des deux têtes de l’exécutif seront clairement réparties. La composition du tandem obéira à un certain nombre de critères comme l’absence totale de parenté de sang ou d’alliance.', '2024-03-20'),
  (3, 1, 'sans_position', 'aucune', null, null, null),
  (3, 2, 'sans_position', 'aucune', null, null, null),
  (3, 3, 'sans_position', 'aucune', null, null, null),
  (3, 4, 'sans_position', 'aucune', null, null, null),
  (3, 5, 'sans_position', 'aucune', null, null, null),
  (3, 6, 'sans_position', 'aucune', null, null, null),
  (3, 7, 'sans_position', 'aucune', null, null, null),
  (3, 8, 'sans_position', 'aucune', null, null, null),
  (3, 9, 'sans_position', 'aucune', null, null, null),
  (3, 13, 'sans_position', 'aucune', null, null, null),
  (4, 1, 'sans_position', 'aucune', null, null, null),
  (4, 2, 'sans_position', 'aucune', null, null, null),
  (4, 3, 'sans_position', 'aucune', null, null, null),
  (4, 4, 'sans_position', 'aucune', null, null, null),
  (4, 5, 'sans_position', 'aucune', null, null, null),
  (4, 6, 'sans_position', 'aucune', null, null, null),
  (4, 7, 'sans_position', 'aucune', null, null, null),
  (4, 8, 'sans_position', 'aucune', null, null, null),
  (4, 9, 'sans_position', 'aucune', null, null, null),
  (4, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Nous instituerons l’indépendance du parquet vis-à-vis du Ministre de la Justice et le renforcement du statut « spécial » du parquet. Ainsi, la suppression de toute possibilité pour le ministère de la Justice de donner des instructions au ministère publique sur la gestion des dossiers sera actée, notamment par :', '2024-03-20'),
  (5, 1, 'sans_position', 'aucune', null, null, null),
  (5, 2, 'sans_position', 'aucune', null, null, null),
  (5, 3, 'sans_position', 'aucune', null, null, null),
  (5, 4, 'sans_position', 'aucune', null, null, null),
  (5, 5, 'sans_position', 'aucune', null, null, null),
  (5, 6, 'sans_position', 'aucune', null, null, null),
  (5, 7, 'sans_position', 'aucune', null, null, null),
  (5, 8, 'sans_position', 'aucune', null, null, null),
  (5, 9, 'sans_position', 'aucune', null, null, null),
  (5, 13, 'sans_position', 'aucune', null, null, null),
  (6, 1, 'sans_position', 'aucune', null, null, null),
  (6, 2, 'sans_position', 'aucune', null, null, null),
  (6, 3, 'sans_position', 'aucune', null, null, null),
  (6, 4, 'sans_position', 'aucune', null, null, null),
  (6, 5, 'sans_position', 'aucune', null, null, null),
  (6, 6, 'neutre', 'document_public', 'https://parti-pur.com/wp-content/uploads/2024/01/RESUME-PROGRAMME-AMD.pdf', 'Le plan de financement de ce programme est abordé hors ressources pétrolières et gazières, en attendant d’évaluer et d’analyser de tous les contrats signés par l’Etat du Sénégal et de statuer de manière plus consensuelle sur leur utilisation.', '2024-01-10'),
  (6, 7, 'sans_position', 'aucune', null, null, null),
  (6, 8, 'sans_position', 'aucune', null, null, null),
  (6, 9, 'sans_position', 'aucune', null, null, null),
  (6, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Sous-secteur hydrocarbures : Nous réorganiserons institutionnellement le secteur des hydrocarbures et renégocierons les contrats pour maximiser les revenus issus de l’exploitation pétrolière ; […] Nous soumettrons la validation des contrats pétroliers à l’approbation parlementaire préalable conformément à l’article 25-1 de la Constitution qui stipule que « Les ressources naturelles appartiennent au peuple. Elles sont utilisées pour l’amélioration', '2024-03-20'),
  (7, 1, 'sans_position', 'aucune', null, null, null),
  (7, 2, 'sans_position', 'aucune', null, null, null),
  (7, 3, 'sans_position', 'aucune', null, null, null),
  (7, 4, 'sans_position', 'aucune', null, null, null),
  (7, 5, 'sans_position', 'aucune', null, null, null),
  (7, 6, 'sans_position', 'aucune', null, null, null),
  (7, 7, 'sans_position', 'aucune', null, null, null),
  (7, 8, 'sans_position', 'aucune', null, null, null),
  (7, 9, 'sans_position', 'aucune', null, null, null),
  (7, 13, 'sans_position', 'aucune', null, null, null),
  (8, 1, 'sans_position', 'aucune', null, null, null),
  (8, 2, 'sans_position', 'aucune', null, null, null),
  (8, 3, 'sans_position', 'aucune', null, null, null),
  (8, 4, 'sans_position', 'aucune', null, null, null),
  (8, 5, 'sans_position', 'aucune', null, null, null),
  (8, 6, 'neutre', 'document_public', 'https://parti-pur.com/wp-content/uploads/2024/01/RESUME-PROGRAMME-AMD.pdf', 'Concernant le Pilier 2, la réalisation de ses objectifs passera par la mise en œuvre des priorités stratégiques suivantes : 1. Une augmentation de la production du secteur primaire, 2. Un réaménagement du climat des affaires au profit du secteur privé national, 3. Une promotion de l’accès des femmes et des jeunes aux ressources productives, 4. Un désamorçage de la bombe du chômage, 5. Une protection de l’environnement et des ressources naturelles, 6. Une promotion d’un tissu industriel moderne, performant et compétitif, 7. Une souveraineté monétaire, 8. Une promotion de l''artisanat.', '2024-01-10'),
  (8, 7, 'sans_position', 'aucune', null, null, null),
  (8, 8, 'sans_position', 'aucune', null, null, null),
  (8, 9, 'sans_position', 'aucune', null, null, null),
  (8, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'L’état du Sénégal se trouve bâillonné par son appartenance à la zone franc CFA. […] Nous mettrons en œuvre une réforme monétaire qui permettra à notre pays de se doter de sa propre monnaie. […] Pour les réformes monétaires, le délai de réalisation dépendra du scénario retenu : Une sortie du FCFA du Sénégal tout seul ; Une sortie du FCFA avec d’autres pays de la l’UEMOA ou de la CEDEAO.', '2024-03-20'),
  (9, 1, 'sans_position', 'aucune', null, null, null),
  (9, 2, 'sans_position', 'aucune', null, null, null),
  (9, 3, 'sans_position', 'aucune', null, null, null),
  (9, 4, 'sans_position', 'aucune', null, null, null),
  (9, 5, 'sans_position', 'aucune', null, null, null),
  (9, 6, 'sans_position', 'aucune', null, null, null),
  (9, 7, 'sans_position', 'aucune', null, null, null),
  (9, 8, 'sans_position', 'aucune', null, null, null),
  (9, 9, 'sans_position', 'aucune', null, null, null),
  (9, 13, 'sans_position', 'aucune', null, null, null),
  (10, 1, 'sans_position', 'aucune', null, null, null),
  (10, 2, 'sans_position', 'aucune', null, null, null),
  (10, 3, 'sans_position', 'aucune', null, null, null),
  (10, 4, 'sans_position', 'aucune', null, null, null),
  (10, 5, 'sans_position', 'aucune', null, null, null),
  (10, 6, 'sans_position', 'aucune', null, null, null),
  (10, 7, 'sans_position', 'aucune', null, null, null),
  (10, 8, 'sans_position', 'aucune', null, null, null),
  (10, 9, 'sans_position', 'aucune', null, null, null),
  (10, 13, 'neutre', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Ainsi, il est d’une nécessité absolue de maîtriser notre dette publique et d’utiliser des stratégies avec des coûts économiques et sociaux à court, moyen et long terme très faibles. Nous mettrons en œuvre une stratégie de ralentissement de la vitesse d’accroissement de la dette par : La réduction graduelle et intelligente du déficit budgétaire, par l’amélioration de la qualité des dépenses publiques, et une fiscalité plus efficace économiquement et socialement ;', '2024-03-20'),
  (11, 1, 'sans_position', 'aucune', null, null, null),
  (11, 2, 'sans_position', 'aucune', null, null, null),
  (11, 3, 'sans_position', 'aucune', null, null, null),
  (11, 4, 'sans_position', 'aucune', null, null, null),
  (11, 5, 'sans_position', 'aucune', null, null, null),
  (11, 6, 'sans_position', 'aucune', null, null, null),
  (11, 7, 'sans_position', 'aucune', null, null, null),
  (11, 8, 'sans_position', 'aucune', null, null, null),
  (11, 9, 'sans_position', 'aucune', null, null, null),
  (11, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Nous suspendrons et évaluerons tous les accords de pêche de la zone économique exclusive et auditerons le pavillon sénégalais ;', '2024-03-20'),
  (12, 1, 'sans_position', 'aucune', null, null, null),
  (12, 2, 'sans_position', 'aucune', null, null, null),
  (12, 3, 'sans_position', 'aucune', null, null, null),
  (12, 4, 'sans_position', 'aucune', null, null, null),
  (12, 5, 'sans_position', 'aucune', null, null, null),
  (12, 6, 'sans_position', 'aucune', null, null, null),
  (12, 7, 'sans_position', 'aucune', null, null, null),
  (12, 8, 'sans_position', 'aucune', null, null, null),
  (12, 9, 'sans_position', 'aucune', null, null, null),
  (12, 13, 'sans_position', 'aucune', null, null, null),
  (13, 1, 'sans_position', 'aucune', null, null, null),
  (13, 2, 'sans_position', 'aucune', null, null, null),
  (13, 3, 'sans_position', 'aucune', null, null, null),
  (13, 4, 'sans_position', 'aucune', null, null, null),
  (13, 5, 'sans_position', 'aucune', null, null, null),
  (13, 6, 'sans_position', 'aucune', null, null, null),
  (13, 7, 'sans_position', 'aucune', null, null, null),
  (13, 8, 'sans_position', 'aucune', null, null, null),
  (13, 9, 'sans_position', 'aucune', null, null, null),
  (13, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Nous généraliserons l’utilisation des langues nationales dans le système d’éducation et de formation, comme recommandée par les Assises sur l’éducation et la formation, en capitalisant les expérimentations probantes afin d’en faire des langues objet et medium d’enseignement ;', '2024-03-20'),
  (14, 1, 'sans_position', 'aucune', null, null, null),
  (14, 2, 'sans_position', 'aucune', null, null, null),
  (14, 3, 'sans_position', 'aucune', null, null, null),
  (14, 4, 'sans_position', 'aucune', null, null, null),
  (14, 5, 'sans_position', 'aucune', null, null, null),
  (14, 6, 'neutre', 'document_public', 'https://parti-pur.com/wp-content/uploads/2024/01/RESUME-PROGRAMME-AMD.pdf', 'Malgré la performance attendue de ces piliers et leviers d’accélérations, le président Aliou Mamadou DIA compte apporter des réformes phares pour répondre efficacement aux besoins des sénégalais. Il s’agit : 1. Du Conseil Supérieur de la Jeunesse (CSJ), 2. Des Pôles de Développement Durable (P2D), 3. De la Professionnalisation des « Daaras », 4. Du Haut Conseil des Sages (HCS),', '2024-01-10'),
  (14, 7, 'sans_position', 'aucune', null, null, null),
  (14, 8, 'sans_position', 'aucune', null, null, null),
  (14, 9, 'sans_position', 'aucune', null, null, null),
  (14, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Ainsi, il est important de donner plus de poids aux langues nationales et d’intégrer les « daaras » dans le système éducatif sénégalais. […] Nous renforcerons le Projet d''Appui à la Modernisation des Daaras (PAMOD) et procéderons à une cartographie participative et exhaustive de l’ensemble des daaras et écoles coraniques du Sénégal. Le statut du maître coranique sera clairement établi en […] L’intégration des daaras et des écoles coraniques dans le système d’éducation et de formation ;', '2024-03-20'),
  (15, 1, 'sans_position', 'aucune', null, null, null),
  (15, 2, 'sans_position', 'aucune', null, null, null),
  (15, 3, 'sans_position', 'aucune', null, null, null),
  (15, 4, 'sans_position', 'aucune', null, null, null),
  (15, 5, 'sans_position', 'aucune', null, null, null),
  (15, 6, 'sans_position', 'aucune', null, null, null),
  (15, 7, 'sans_position', 'aucune', null, null, null),
  (15, 8, 'sans_position', 'aucune', null, null, null),
  (15, 9, 'sans_position', 'aucune', null, null, null),
  (15, 13, 'sans_position', 'aucune', null, null, null),
  (16, 1, 'sans_position', 'aucune', null, null, null),
  (16, 2, 'sans_position', 'aucune', null, null, null),
  (16, 3, 'sans_position', 'aucune', null, null, null),
  (16, 4, 'sans_position', 'aucune', null, null, null),
  (16, 5, 'sans_position', 'aucune', null, null, null),
  (16, 6, 'sans_position', 'aucune', null, null, null),
  (16, 7, 'sans_position', 'aucune', null, null, null),
  (16, 8, 'sans_position', 'aucune', null, null, null),
  (16, 9, 'sans_position', 'aucune', null, null, null),
  (16, 13, 'neutre', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Nous mettrons en place la couverture sanitaire universelle (CSU) en lieu et place de la couverture maladie universelle (CMU), pour mieux prendre en compte la politique de prévention et travailler à éviter la maladie. Pour être efficace, la CSU bénéficiera à tout le monde et impliquera la grande majorité dans la cotisation ; […] Nous augmenterons progressivement la contribution des ménages à la CSU avec à terme une cotisation obligatoire et régulière avec un accompagnement des couches vulnérables ;', '2024-03-20'),
  (17, 1, 'sans_position', 'aucune', null, null, null),
  (17, 2, 'sans_position', 'aucune', null, null, null),
  (17, 3, 'sans_position', 'aucune', null, null, null),
  (17, 4, 'sans_position', 'aucune', null, null, null),
  (17, 5, 'sans_position', 'aucune', null, null, null),
  (17, 6, 'sans_position', 'aucune', null, null, null),
  (17, 7, 'sans_position', 'aucune', null, null, null),
  (17, 8, 'sans_position', 'aucune', null, null, null),
  (17, 9, 'sans_position', 'aucune', null, null, null),
  (17, 13, 'sans_position', 'aucune', null, null, null),
  (18, 1, 'sans_position', 'aucune', null, null, null),
  (18, 2, 'sans_position', 'aucune', null, null, null),
  (18, 3, 'sans_position', 'aucune', null, null, null),
  (18, 4, 'sans_position', 'aucune', null, null, null),
  (18, 5, 'sans_position', 'aucune', null, null, null),
  (18, 6, 'sans_position', 'aucune', null, null, null),
  (18, 7, 'sans_position', 'aucune', null, null, null),
  (18, 8, 'sans_position', 'aucune', null, null, null),
  (18, 9, 'sans_position', 'aucune', null, null, null),
  (18, 13, 'sans_position', 'aucune', null, null, null),
  (19, 1, 'sans_position', 'aucune', null, null, null),
  (19, 2, 'sans_position', 'aucune', null, null, null),
  (19, 3, 'sans_position', 'aucune', null, null, null),
  (19, 4, 'sans_position', 'aucune', null, null, null),
  (19, 5, 'sans_position', 'aucune', null, null, null),
  (19, 6, 'sans_position', 'aucune', null, null, null),
  (19, 7, 'sans_position', 'aucune', null, null, null),
  (19, 8, 'sans_position', 'aucune', null, null, null),
  (19, 9, 'sans_position', 'aucune', null, null, null),
  (19, 13, 'sans_position', 'aucune', null, null, null),
  (20, 1, 'sans_position', 'aucune', null, null, null),
  (20, 2, 'sans_position', 'aucune', null, null, null),
  (20, 3, 'sans_position', 'aucune', null, null, null),
  (20, 4, 'sans_position', 'aucune', null, null, null),
  (20, 5, 'sans_position', 'aucune', null, null, null),
  (20, 6, 'sans_position', 'aucune', null, null, null),
  (20, 7, 'sans_position', 'aucune', null, null, null),
  (20, 8, 'sans_position', 'aucune', null, null, null),
  (20, 9, 'sans_position', 'aucune', null, null, null),
  (20, 13, 'sans_position', 'aucune', null, null, null),
  (21, 1, 'sans_position', 'aucune', null, null, null),
  (21, 2, 'sans_position', 'aucune', null, null, null),
  (21, 3, 'sans_position', 'aucune', null, null, null),
  (21, 4, 'sans_position', 'aucune', null, null, null),
  (21, 5, 'sans_position', 'aucune', null, null, null),
  (21, 6, 'sans_position', 'aucune', null, null, null),
  (21, 7, 'sans_position', 'aucune', null, null, null),
  (21, 8, 'sans_position', 'aucune', null, null, null),
  (21, 9, 'sans_position', 'aucune', null, null, null),
  (21, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'Augmentation de l’indexation des fonds de dotation et des fonds d’équipement faite sur la TVA pour la faire passer de 5,5% à un taux de 10% voire 15% ;', '2024-03-20'),
  (22, 1, 'sans_position', 'aucune', null, null, null),
  (22, 2, 'sans_position', 'aucune', null, null, null),
  (22, 3, 'sans_position', 'aucune', null, null, null),
  (22, 4, 'sans_position', 'aucune', null, null, null),
  (22, 5, 'sans_position', 'aucune', null, null, null),
  (22, 6, 'sans_position', 'aucune', null, null, null),
  (22, 7, 'sans_position', 'aucune', null, null, null),
  (22, 8, 'sans_position', 'aucune', null, null, null),
  (22, 9, 'sans_position', 'aucune', null, null, null),
  (22, 13, 'accord', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'L''usage de produits biodégradables et l’application stricte de la loi sur le plastique ;', '2024-03-20'),
  (23, 1, 'sans_position', 'aucune', null, null, null),
  (23, 2, 'sans_position', 'aucune', null, null, null),
  (23, 3, 'sans_position', 'aucune', null, null, null),
  (23, 4, 'sans_position', 'aucune', null, null, null),
  (23, 5, 'sans_position', 'aucune', null, null, null),
  (23, 6, 'sans_position', 'aucune', null, null, null),
  (23, 7, 'sans_position', 'aucune', null, null, null),
  (23, 8, 'sans_position', 'aucune', null, null, null),
  (23, 9, 'sans_position', 'aucune', null, null, null),
  (23, 13, 'neutre', 'document_public', 'https://web.archive.org/web/20250407124403id_/https://diomayepresident.org/wp-content/uploads/2024/03/Livre-Programme-Bassirou-Diomaye-Faye.pdf', 'des approches intégrées qui offrent au pays des options concernant l’exploitation de leurs potentiels en ressources en hydrocarbures (pétrole et gaz) […] L''équité doit être un principe central guidant la réduction progressive des combustibles fossiles afin de ne pas aggraver les inégalités dont le secteur extractif a souffert.', '2024-03-20'),
  (24, 1, 'sans_position', 'aucune', null, null, null),
  (24, 2, 'sans_position', 'aucune', null, null, null),
  (24, 3, 'sans_position', 'aucune', null, null, null),
  (24, 4, 'sans_position', 'aucune', null, null, null),
  (24, 5, 'sans_position', 'aucune', null, null, null),
  (24, 6, 'sans_position', 'aucune', null, null, null),
  (24, 7, 'sans_position', 'aucune', null, null, null),
  (24, 8, 'sans_position', 'aucune', null, null, null),
  (24, 9, 'sans_position', 'aucune', null, null, null),
  (24, 13, 'sans_position', 'aucune', null, null, null),
  (25, 1, 'sans_position', 'aucune', null, null, null),
  (25, 2, 'sans_position', 'aucune', null, null, null),
  (25, 3, 'sans_position', 'aucune', null, null, null),
  (25, 4, 'sans_position', 'aucune', null, null, null),
  (25, 5, 'sans_position', 'aucune', null, null, null),
  (25, 6, 'sans_position', 'aucune', null, null, null),
  (25, 7, 'sans_position', 'aucune', null, null, null),
  (25, 8, 'sans_position', 'aucune', null, null, null),
  (25, 9, 'sans_position', 'aucune', null, null, null),
  (25, 13, 'sans_position', 'aucune', null, null, null);

-- Une fois relu : update public.quiz set publie = true where id = 1;

select setval('public.person_id_seq', (select coalesce(max(id), 1) from public.person));
select setval('public.organization_id_seq', (select coalesce(max(id), 1) from public.organization));
select setval('public.portfolio_id_seq', (select coalesce(max(id), 1) from public.portfolio));
select setval('public.role_id_seq', (select coalesce(max(id), 1) from public.role));
select setval('public.government_id_seq', (select coalesce(max(id), 1) from public.government));
select setval('public.mandate_id_seq', (select coalesce(max(id), 1) from public.mandate));
select setval('public.legislature_id_seq', (select coalesce(max(id), 1) from public.legislature));
select setval('public.constituency_id_seq', (select coalesce(max(id), 1) from public.constituency));
select setval('public.quiz_id_seq', (select coalesce(max(id), 1) from public.quiz));
select setval('public.statement_id_seq', (select coalesce(max(id), 1) from public.statement));

commit;
