name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  analyse-et-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.3'
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
